#!/bin/bash
set -e
IP="16.171.12.89"
echo "=== Testing All Services ==="
echo ""
echo "1. Discovery Service (8761):"
curl -s http://$IP:8761/actuator/health | grep -o '"status":"[^"]*"' || echo "FAILED"
echo ""
echo "2. Auth Service - Register (8081):"
REGISTER=$(curl -s -X POST http://$IP:8081/auth/register -H "Content-Type: application/json" -d '{"email":"test'$(date +%s)'@test.com","password":"Test@123","firstName":"Test","lastName":"User"}')
echo $REGISTER | grep -o '"accessToken":"[^"]*"' | head -c 50 || echo "FAILED"
TOKEN=$(echo $REGISTER | grep -o '"accessToken":"[^"]*' | cut -d'"' -f4)
echo ""
echo "3. Auth Service - Login (8081):"
curl -s -X POST http://$IP:8081/auth/login -H "Content-Type: application/json" -d '{"email":"admin2@shopsphere.com","password":"Admin@123"}' | grep -o '"role":"[^"]*"' || echo "FAILED"
echo ""
echo "4. Auth Service - Validate (8081):"
curl -s -X POST http://$IP:8081/auth/validate -H "Authorization: Bearer $TOKEN" | head -c 100 || echo "FAILED"
echo ""
echo "5. Admin Service Direct (8089):"
curl -s http://$IP:8089/admin/api/v1/dashboard/overview | grep -o '"serviceStatus":"[^"]*"' || echo "FAILED"
echo ""
echo "6. API Gateway - Auth Route (8080):"
curl -s -X POST http://$IP:8080/auth/login -H "Content-Type: application/json" -d '{"email":"admin2@shopsphere.com","password":"Admin@123"}' | grep -o '"role":"[^"]*"' || echo "FAILED"
echo ""
echo "7. API Gateway - Admin Route (8080):"
docker exec -i auth-db psql -U postgres -d shopsphere_auth -c "UPDATE users SET role = 'ADMIN' WHERE email = 'admin2@shopsphere.com';" > /dev/null
LOGIN=$(curl -s -X POST http://$IP:8080/auth/login -H "Content-Type: application/json" -d '{"email":"admin2@shopsphere.com","password":"Admin@123"}')
ADMIN_TOKEN=$(echo $LOGIN | grep -o '"accessToken":"[^"]*' | cut -d'"' -f4)
curl -s http://$IP:8080/admin/api/v1/dashboard/overview -H "Authorization: Bearer $ADMIN_TOKEN" | grep -o '"serviceStatus":"[^"]*"' || echo "FAILED"
echo ""
echo "8. Analytics Service - Health (8090):"
curl -s -X POST http://$IP:8090/analytics/api/v1/health | grep -o '"data":"[^"]*"' || echo "FAILED"
echo ""
echo "9. Analytics Service - Ingest Event (8090):"
curl -s -X POST "http://$IP:8090/analytics/api/v1/events?eventType=ORDER_PLACED&userId=1&sessionId=sess$(date +%s)" -H "Content-Type: application/json" -d '{"orderId":123,"amount":99.99}' | grep -o '"data":"[^"]*"' || echo "FAILED"
echo ""
echo "10. Analytics Service - Get Count (8090):"
BEFORE_COUNT=$(curl -s http://$IP:8090/analytics/api/v1/count | grep -o '"data":[0-9]*' | cut -d':' -f2)
echo "Before: $BEFORE_COUNT"
echo ""
echo "11. Kafka - Send Event to user-events topic:"
echo '{"eventType":"PRODUCT_CLICKED","userId":999,"sessionId":"kafka-test","productId":777}' | docker exec -i kafka /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic user-events --property "parse.key=false" 2>&1 | head -1 || echo "SENT"
echo ""
echo "12. Kafka - Verify event consumed (wait 3s):"
sleep 3
AFTER_COUNT=$(curl -s http://$IP:8090/analytics/api/v1/count | grep -o '"data":[0-9]*' | cut -d':' -f2)
echo "After: $AFTER_COUNT"
if [ "$AFTER_COUNT" -gt "$BEFORE_COUNT" ]; then echo "✓ Kafka working"; else echo "✗ Kafka failed"; fi
echo ""
echo "13. Catalog Service - Health (8083):"
curl -s http://$IP:8083/actuator/health | grep -o '"status":"[^"]*"' || echo "FAILED"
echo ""
echo "14. Catalog Service - Get Categories (8083):"
curl -s http://$IP:8083/api/v1/categories | grep -o '"name":"[^"]*"' | head -1 || echo "FAILED"
echo ""
echo "15. Catalog Service - Create Product (8083):"
PROD=$(curl -s -X POST http://$IP:8083/api/v1/products -H "Content-Type: application/json" -d '{"sku":"TEST-'$(date +%s)'","name":"Test Product","price":99.99,"categoryId":"693844e81617aa0c42ade0a2"}')
echo $PROD | grep -o '"name":"[^"]*"' || echo "FAILED"
echo ""
echo "16. Discovery Service - Registered Apps:"
curl -s http://$IP:8761/eureka/apps | grep "<app>" | wc -l
echo ""
echo "17. Batch Service - Health (8091):"
curl -s http://$IP:8091/actuator/health | grep -o '"status":"[^"]*"' || echo "FAILED"
echo ""
echo "18. Batch Service - List Jobs (8091):"
curl -s http://$IP:8091/api/v1/batch/jobs | grep -o '"success":[^,]*' || echo "FAILED"
echo ""
echo "=== Test Complete ===" 