#!/bin/bash
set -e
IP="16.171.12.89"
echo "=== Testing Catalog Service ==="
echo ""
echo "1. Health Check:"
curl -s http://$IP:8083/actuator/health | grep -o '"status":"[^"]*"' || echo "FAILED"
echo ""
echo "2. Create Category:"
CATEGORY=$(curl -s -X POST http://$IP:8083/api/v1/categories -H "Content-Type: application/json" -d '{"name":"Books'$(date +%s)'","description":"Books and literature"}')
CATEGORY_ID=$(echo $CATEGORY | grep -o '"id":"[^"]*' | cut -d'"' -f4)
echo $CATEGORY | grep -o '"name":"[^"]*"' || echo "FAILED"
echo ""
echo "3. Update Category:"
curl -s -X PUT http://$IP:8083/api/v1/categories/$CATEGORY_ID -H "Content-Type: application/json" -d '{"name":"Books'$(date +%s)'","description":"Updated description"}' | grep -o '"description":"[^"]*"' || echo "FAILED"
echo ""
echo "4. Get All Categories:"
curl -s http://$IP:8083/api/v1/categories | grep -o '"name":"[^"]*"' | head -2 || echo "FAILED"
echo ""
echo "5. Create Product (triggers Kafka event):"
PRODUCT=$(curl -s -X POST http://$IP:8083/api/v1/products -H "Content-Type: application/json" -d '{"sku":"BOOK-'$(date +%s)'","name":"Test Book","description":"A great book","price":29.99,"categoryId":"'$CATEGORY_ID'","images":["book.jpg"]}')
echo $PRODUCT | grep -o '"name":"[^"]*"' || echo "FAILED"
PRODUCT_ID=$(echo $PRODUCT | grep -o '"id":"[^"]*' | cut -d'"' -f4)
echo ""
echo "6. Get Product by ID:"
curl -s http://$IP:8083/api/v1/products/$PRODUCT_ID | grep -o '"name":"[^"]*"' || echo "FAILED"
echo ""
echo "7. Update Product (triggers Kafka event):"
curl -s -X PUT http://$IP:8083/api/v1/products/$PRODUCT_ID -H "Content-Type: application/json" -d '{"name":"Updated Book","price":39.99}' | grep -o '"name":"[^"]*"' || echo "FAILED"
echo ""
echo "8. Get Product by SKU:"
PROD_SKU=$(echo $PRODUCT | grep -o '"sku":"[^"]*' | cut -d'"' -f4)
curl -s http://$IP:8083/api/v1/products/sku/$PROD_SKU | grep -o '"sku":"[^"]*"' || echo "FAILED"
echo ""
echo "9. Get All Products (paginated):"
curl -s http://$IP:8083/api/v1/products | grep -o '"totalElements":[0-9]*' || echo "FAILED"
echo ""
echo "10. Get Products by Category:"
curl -s http://$IP:8083/api/v1/products/category/$CATEGORY_ID | grep -o '"totalElements":[0-9]*' || echo "FAILED"
echo ""
echo "11. Get Products by Status:"
curl -s http://$IP:8083/api/v1/products/status/ACTIVE | grep -o '"totalElements":[0-9]*' || echo "FAILED"
echo ""
echo "12. Search Products:"
curl -s "http://$IP:8083/api/v1/products/search?keyword=book" | grep -o '"name":"[^"]*"' | head -1 || echo "FAILED"
echo ""
echo "13. Kafka - Check product-events topic:"
docker exec kafka /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic product-events --from-beginning --max-messages 2 --timeout-ms 3000 2>/dev/null | grep -c "PRODUCT" || echo "0 events"
echo ""
echo "14. Eureka Registration:"
curl -s http://$IP:8761/eureka/apps | grep -i "CATALOG-SERVICE" > /dev/null && echo "✓ Registered" || echo "✗ Not registered"
echo ""
echo "15. Via Gateway - Get Categories:"
curl -s http://$IP:8080/api/v1/categories | grep -o '"name":"[^"]*"' | head -1 || echo "FAILED"
echo ""
echo "=== Catalog Service Tests Complete ==="
